INSERT INTO cnf_configuracion_catalogo (id, dominio, tipo, descripcion, valor_default) VALUES (1, 'Relojes', 'Marca', 'Catalogo de marcas de reloj', null);
INSERT INTO cnf_configuracion_catalogo (id, dominio, tipo, descripcion, valor_default) VALUES (2, 'Relojes', 'TipoReloj', 'Catalogo de tipos de reloj', null);
INSERT INTO cnf_configuracion_catalogo (id, dominio, tipo, descripcion, valor_default) VALUES (3, 'Relojes', 'CondicionesGenerales', 'Catalogo de condiciones generales del reloj', null);
INSERT INTO cnf_configuracion_catalogo (id, dominio, tipo, descripcion, valor_default) VALUES (4, 'Relojes', 'DesplazamientoComercial', 'Catalogo de desplazamiento comercial del reloj', null);
INSERT INTO cnf_configuracion_catalogo (id, dominio, tipo, descripcion, valor_default) VALUES (5, 'Relojes', 'Genero', 'Catalogo de genero del reloj', null);
INSERT INTO cnf_configuracion_catalogo (id, dominio, tipo, descripcion, valor_default) VALUES (6, 'Relojes', 'MatrizCoordenadas', 'Catalogo de matriz de coordenadas', null);
INSERT INTO cnf_configuracion_catalogo (id, dominio, tipo, descripcion, valor_default) VALUES (7, 'Relojes', 'Refrendos', 'Catalogo de refrendos segun tipo de reloj', null);


INSERT INTO cnf_entidad_catalogo (id, catalogo, entidad) VALUES (1, 'MARCA', 'mx.com.nmp.ms.sivar.catalogo.domain.Marca');
INSERT INTO cnf_entidad_catalogo (id, catalogo, entidad) VALUES (2, 'TIPO_RELOJ', 'mx.com.nmp.ms.sivar.catalogo.domain.TipoReloj');
INSERT INTO cnf_entidad_catalogo (id, catalogo, entidad) VALUES (3, 'CONDICIONES_GENERALES', 'mx.com.nmp.ms.sivar.catalogo.domain.CondicionesGenerales');
INSERT INTO cnf_entidad_catalogo (id, catalogo, entidad) VALUES (4, 'DESPLAZAMIENTO_COMERCIAL', 'mx.com.nmp.ms.sivar.catalogo.domain.DesplazamientoComercial');
INSERT INTO cnf_entidad_catalogo (id, catalogo, entidad) VALUES (5, 'GENERO', 'mx.com.nmp.ms.sivar.catalogo.domain.Genero');


INSERT INTO cat_tipo_reloj (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (1, 'AUTO', 'Automático', 2);
INSERT INTO cat_tipo_reloj (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (2, 'CURZ', 'Cuarzo', 2);
INSERT INTO cat_tipo_reloj (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (3, 'MANL', 'Cuerda manual', 2);


INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (1, 'OTRO', 'Otro', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (2, 'LANG', 'A. LANGE & SÖHNE', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (3, 'ACCU', 'Accutron', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (4, 'ADID', 'Adidas', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (5, 'AERO', 'Aerowatch', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (6, 'AIGN', 'Aigner', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (7, 'ALAI', 'Alain Silberstein', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (8, 'ALEX', 'Alexander Shorokhoff', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (9, 'ALFR', 'Alfred Dunhill', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (10, 'ALMA', 'Almanus', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (11, 'ALPI', 'Alpina', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (12, 'ALTA', 'Altanus', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (13, 'ANDE', 'Andersen Genève', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (14, 'ANGE', 'Angelus', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (15, 'ANGU', 'Angular Momentum', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (16, 'ANON', 'Anonimo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (17, 'AQUA', 'Aquanautic', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (18, 'ARIS', 'Aristo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (19, 'ARNI', 'Armand Nicolet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (20, 'ARMA', 'Armani', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (21, 'ARMI', 'Armin Strom', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (22, 'ARNO', 'Arnold & Son', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (23, 'ARTY', 'Artya', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (24, 'ASKA', 'Askania', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (25, 'ATLA', 'Atlantic', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (26, 'AUDE', 'Audemars Piguet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (27, 'AUGU', 'Auguste Reymond', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (28, 'AURI', 'Auricoste', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (29, 'AZIM', 'Azimuth', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (30, 'AZZA', 'Azzaro', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (31, 'B.R.', 'B.R.M', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (32, 'BALL', 'Ball', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (33, 'BART', 'Barthelay', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (34, 'BASI', 'Basilika', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (35, 'BAUM', 'Baume & Mercier', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (36, 'BEDA', 'Bedat & Co', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (37, 'BELL', 'Bell & Ross', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (38, 'BELT', 'Beltonn', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (39, 'BENR', 'Benrus', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (40, 'BENZ', 'Benzinger', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (41, 'BERT', 'Bertolucci', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (42, 'BLOC', 'Black-Out Concept', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (43, 'BLAC', 'Blacksand', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (44, 'BLAN', 'Blancpain', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (45, 'BLU', 'blu', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (46, 'BOEG', 'Boegli', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (47, 'BOGN', 'Bogner Time', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (48, 'BOMB', 'Bombardier', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (49, 'BOUC', 'Boucheron', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (50, 'BOVE', 'Bovet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (51, 'BREG', 'Breguet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (52, 'BREI', 'Breil', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (53, 'BRNG', 'Breitling', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (54, 'BREM', 'Bremont', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (55, 'BRIO', 'Brior', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (56, 'BRUN', 'Bruno Söhnle', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (57, 'BUBE', 'Buben & Zörweg', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (58, 'BUCH', 'Bucherer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (59, 'BULG', 'Bulgari', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (60, 'BULO', 'Bulova', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (61, 'BUNZ', 'Bunz', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (62, 'BURB', 'Burberry', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (63, 'BWC-', 'BWC-Swiss', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (64, 'CAME', 'Camel Active', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (65, 'CAMI', 'Camille Fournet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (66, 'CAND', 'Candino', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (67, 'CARL', 'Carl F. Bucherer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (68, 'CARF', 'Carlo Ferrara', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (69, 'CARR', 'Carrera', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (70, 'CART', 'Cartier', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (71, 'CASI', 'Casio', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (72, 'CATE', 'Catena', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (73, 'CATO', 'Catorex', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (74, 'CATT', 'Cattin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (75, 'CEDR', 'Cedric Johner', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (76, 'CENT', 'Century', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (77, 'CERR', 'Cerruti', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (78, 'CERT', 'Certina', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (79, 'CHAN', 'Chanel', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (80, 'CHEX', 'Charmex', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (81, 'CHAR', 'Charriol', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (82, 'CHAS', 'Chase-Durer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (83, 'CHAU', 'Chaumet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (84, 'CHOP', 'Chopard', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (85, 'CHBE', 'Chris Benz', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (86, 'CHKL', 'Christiaan v.d. Klaauw', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (87, 'CHSU', 'Chronographe Suisse Cie', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (88, 'CHRN', 'Chronosport', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (89, 'CHRO', 'Chronoswiss', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (90, 'CHUR', 'Churpfälzische Uhrenmanufaktur', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (91, 'CITI', 'Citizen', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (92, 'CK C', 'ck Calvin Klein', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (93, 'CLAS', 'Classic Watch Construction', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (94, 'CLAU', 'Claude Meylan', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (95, 'CLER', 'Clerc', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (96, 'CONC', 'Concord', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (97, 'COND', 'Condor', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (98, 'CORU', 'Corum', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (99, 'CUER', 'Cuervo y Sobrinos', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (100, 'CVST', 'Cvstos', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (101, 'CWC', 'CWC', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (102, 'CYCL', 'Cyclos', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (103, 'CYMA', 'Cyma', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (104, 'DAMA', 'Damasko', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (105, 'DANI', 'Daniel Roth', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (106, 'DAVI', 'David Yurman', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (107, 'DAVO', 'Davosa', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (108, 'DE B', 'De Bethune', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (109, 'DE G', 'De Grisogono', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (110, 'DECO', 'DeLaCour', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (111, 'DENE', 'DeLaneau', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (112, 'DEVO', 'Devon', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (113, 'DEWI', 'Dewitt', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (114, 'DIES', 'Diesel', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (115, 'DI L', 'Di Lenardo &. Co', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (116, 'DIOR', 'Dior', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (117, 'DKNY', 'DKNY', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (118, 'DOLC', 'Dolce & Gabbana', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (119, 'DOXA', 'Doxa', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (120, 'DUBE', 'Dubey & Schaldenbrand', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (121, 'DUBO', 'DuBois 1785', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (122, 'DUEF', 'DuBois et fils', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (123, 'DUGE', 'Dugena', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (124, 'DWIS', 'Dwiss', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (125, 'EBEL', 'Ebel', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (126, 'EBER', 'Eberhard & Co.', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (127, 'EDC', 'EDC', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (128, 'ED H', 'Ed Hardy', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (129, 'EDOX', 'Edox', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (130, 'ELEC', 'Election', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (131, 'ELGI', 'Elgin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (132, 'ELYS', 'Elysee', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (133, 'ENIC', 'Enicar', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (134, 'ENIG', 'Enigma', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (135, 'EPOS', 'Epos', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (136, 'ERNE', 'Ernest Borel', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (137, 'ERNS', 'Ernst Benz', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (138, 'ERWI', 'Erwin Sattler', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (139, 'ESPR', 'Esprit', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (140, 'ETER', 'Eterna', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (141, 'ETMA', 'Eterna-Matic', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (142, 'F.P.', 'F.P.Journe', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (143, 'FABE', 'Fabergé', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (144, 'FAVR', 'Favre-Leuba', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (145, 'FELD', 'Feldo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (146, 'FEND', 'Fendi', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (147, 'FEST', 'Festina', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (148, 'FLUD', 'Fludo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (149, 'FORM', 'Formex', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (150, 'FORT', 'Fortis', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (151, 'FORU', 'Forum', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (152, 'FOSS', 'Fossil', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (153, 'FRBA', 'Francesco Basile', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (154, 'FRME', 'Franchi Menotti', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (155, 'FRMU', 'Franck Muller', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (156, 'FRVI', 'Franc Vila', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (157, 'FRED', 'Frederique Constant', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (158, 'GANT', 'Gant', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (159, 'GÉRA', 'Gérald Genta', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (160, 'GEVR', 'Gevril', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (161, 'GIRA', 'Girard Perregaux', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (162, 'GIUL', 'Giuliano Mazzuoli', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (163, 'GLAS', 'Glashütte Original', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (164, 'GLYC', 'Glycine', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (165, 'GOLA', 'Golana', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (166, 'GRAF', 'Graf', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (167, 'GRAH', 'Graham', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (168, 'GREU', 'Greubel Forsey', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (169, 'GROV', 'Grovana', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (170, 'GRUE', 'Gruen', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (171, 'GÜBE', 'Gübelin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (172, 'GUB ', 'GUB Glashütte', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (173, 'GUCC', 'Gucci', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (174, 'GUES', 'Guess', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (175, 'GUST', 'Gustafsson & Sjögren', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (176, 'H.MO', 'H.Moser & Cie.', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (177, 'HACH', 'Hacher', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (178, 'HAEM', 'Haemmer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (179, 'HAGA', 'Hagal', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (180, 'HAMI', 'Hamilton', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (181, 'HAND', 'Handwerk', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (182, 'HANH', 'Hanhart', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (183, 'HARR', 'Harry Winston', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (184, 'HARW', 'Harwood', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (185, 'HAUR', 'Haurex', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (186, 'HAUT', 'Hautlence', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (187, 'HD3', 'HD3', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (188, 'HEBD', 'Hebdomas', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (189, 'HENT', 'Hentschel Hamburg', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (190, 'HERM', 'Hermès', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (191, 'HEUE', 'Heuer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (192, 'HIRS', 'Hirsch', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (193, 'HOWA', 'Howard', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (194, 'HUBE', 'Huber', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (195, 'HUBL', 'Hublot', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (196, 'HUGO', 'Hugo Boss', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (197, 'ICE ', 'Ice Watch', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (198, 'IKEP', 'Ikepod', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (199, 'ILLI', 'Illinois', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (200, 'INGE', 'Ingersoll', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (201, 'INVI', 'Invicta', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (202, 'ISSE', 'Issey Miyake', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (203, 'ITAY', 'Itay Noy', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (204, 'IWC', 'IWC', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (205, 'J. C', 'J. Chevalier', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (206, 'JACO', 'Jacob & Co.', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (207, 'JAJE', 'Jacob Jensen', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (208, 'JAET', 'Jacques Etoile', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (209, 'JACQ', 'Jacques Lemans', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (210, 'JAEG', 'Jaeger-LeCoultre', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (211, 'JAER', 'Jaermann & Stübi', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (212, 'JAQU', 'Jaquet-Droz', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (213, 'JB G', 'JB Gioacchino', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (214, 'JEVE', 'Jean d''Eve', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (215, 'JELA', 'Jean Lassale', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (216, 'JEMG', 'Jean-Mairet & Gillman', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (217, 'JEMA', 'Jean Marcel', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (218, 'JAPE', 'Jean Perret', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (219, 'JEAN', 'JeanRichard', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (220, 'JOOP', 'Joop', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (221, 'JORG', 'Jorg Hysek', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (222, 'JÖRG', 'Jörg Schauer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (223, 'JUNG', 'Junghans', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (224, 'JUNK', 'Junkers', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (225, 'JUVE', 'Juvenia', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (226, 'KADL', 'Kadloo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (227, 'KELE', 'Kelek', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (228, 'KHS', 'KHS', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (229, 'KIEN', 'Kienzle', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (230, 'KOBO', 'Kobold', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (231, 'KORL', 'Korloff', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (232, 'KRIE', 'Krieger', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (233, 'KURT', 'Kurt Schaffo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (234, 'L''EP', 'L''Epée', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (235, 'LACO', 'Laco', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (236, 'LACT', 'Lacoste', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (237, 'LANC', 'Lancaster', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (238, 'LAHE', 'Lang & Heyne', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (239, 'LEMA', 'Lemania', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (240, 'LEON', 'Leonidas', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (241, 'LIME', 'Limes', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (242, 'LIBE', 'Lindburgh + Benson', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (243, 'LIWE', 'Linde Werdelin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (244, 'LIP', 'Lip', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (245, 'LOCM', 'Locman', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (246, 'LOGS', 'Longines', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (247, 'LONG', 'Longio', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (248, 'LORE', 'Lorenz', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (249, 'LORU', 'Lorus', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (250, 'LOER', 'Louis Erard', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (251, 'LOMO', 'Louis Moinet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (252, 'LOVU', 'Louis Vuitton', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (253, 'LUCI', 'Lucien Rochat', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (254, 'LUMI', 'Luminox', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (255, 'LÜM-', 'Lüm-Tec', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (256, 'MAGE', 'Magellan', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (257, 'MARC', 'Marcello C.', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (258, 'MART', 'Martin Braun', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (259, 'MARV', 'Marvin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (260, 'MATH', 'Mathey-Tissot', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (261, 'MATT', 'Matthew Norman', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (262, 'MAUB', 'Mauboussin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (263, 'MAMA', 'Maurice de Mauriac', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (264, 'MALA', 'Maurice Lacroix', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (265, 'MB&F', 'Mb&f', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (266, 'MECC', 'Meccaniche Veloci', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (267, 'MEIS', 'Meistersinger', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (268, 'MERC', 'Mercure', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (269, 'MEYE', 'Meyers', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (270, 'MIKO', 'Michael Kors', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (271, 'MICH', 'Michele', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (272, 'MIHE', 'Michel Herbelin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (273, 'MIJO', 'Michel Jordi', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (274, 'MIDO', 'Mido', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (275, 'MILL', 'Milleret', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (276, 'MILU', 'Milus', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (277, 'MINE', 'Minerva', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (278, 'MOMO', 'Momo Design', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (279, 'MONE', 'Mondaine', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (280, 'MODI', 'Mondia', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (281, 'MONC', 'Montblanc', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (282, 'MOGA', 'Montega', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (283, 'MORE', 'Morellato', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (284, 'MOVA', 'Movado', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (285, 'MÜHL', 'Mühle Glashütte', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (286, 'N.B.', 'N.B. Yäeger', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (287, 'N.O.', 'N.O.A', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (288, 'NAUT', 'Nautica', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (289, 'NAFI', 'Nauticfish', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (290, 'NIVA', 'Nivada', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (291, 'NIVR', 'Nivrel', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (292, 'NIXO', 'Nixon', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (293, 'NOMO', 'Nomos', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (294, 'ODM', 'ODM', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (295, 'OFFI', 'Officina del Tempo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (296, 'OLLE', 'Ollech & Wajs', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (297, 'OMEG', 'Omega', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (298, 'ORA', 'Ora', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (299, 'ORAT', 'Orator', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (300, 'ORBI', 'Orbita', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (301, 'ORFI', 'Orfina', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (302, 'ORIE', 'Orient', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (303, 'ORIS', 'Oris', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (304, 'PANE', 'Panerai', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (305, 'PARM', 'Parmigiani Fleurier', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (306, 'PATE', 'Patek Philippe', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (307, 'PAGE', 'Paul Gerber', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (308, 'PAPI', 'Paul Picot', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (309, 'PEQU', 'Pequignet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (310, 'PERI', 'Perigáum', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (311, 'PERR', 'Perrelet', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (312, 'PERS', 'Perseo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (313, 'PHST', 'Philip Stein', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (314, 'PHWA', 'Philip Watch', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (315, 'PIAG', 'Piaget', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (316, 'PICA', 'Pierre Cardin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (317, 'PIDE', 'Pierre DeRoche', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (318, 'PIKU', 'Pierre Kunz', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (319, 'POLI', 'Police', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (320, 'POLJ', 'Poljot', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (321, 'POME', 'Pomellato', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (322, 'PORS', 'Porsche Design', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (323, 'PRYN', 'Pryngeps', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (324, 'PULS', 'Pulsar', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (325, 'PUMA', 'Puma', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (326, 'QUIN', 'Quinting', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (327, 'RADO', 'Rado', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (328, 'RAID', 'Raidillon', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (329, 'RAIN', 'Rainer Brand', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (330, 'RAYM', 'Raymond Weil', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (331, 'REBE', 'Rebellion', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (332, 'REVU', 'Revue Thommen', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (333, 'RGM', 'RGM', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (334, 'RICH', 'Richard Mille', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (335, 'ROAM', 'Roamer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (336, 'ROBE', 'Roberge', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (337, 'ROGE', 'Roger Dubuis', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (338, 'ROLE', 'Rolex', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (339, 'ROMA', 'Romain Jerome', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (340, 'ROTH', 'Rothenschild', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (341, 'RSW', 'RSW', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (342, 'RYSE', 'Ryser Kentfield', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (343, 'S.OL', 'S.Oliver', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (344, 'S.T.', 'S.T. Dupont', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (345, 'SALV', 'Salvatore Ferragamo', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (346, 'SARC', 'Sarcar', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (347, 'SCAL', 'Scalfaro', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (348, 'SCET', 'Schwarz Etienne', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (349, 'SCHW', 'Schwedler', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (350, 'SECT', 'Sector', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (351, 'SEIK', 'Seiko', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (352, 'SEVE', 'Sevenfriday', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (353, 'SHEL', 'Shellman', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (354, 'SINN', 'Sinn', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (355, 'SJÖÖ', 'Sjöö Sandström', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (356, 'SKAG', 'Skagen', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (357, 'SOLV', 'Solvil', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (358, 'SOTH', 'Sothis', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (359, 'SQUA', 'Squale', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (360, 'STEE', 'Steelcraft', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (361, 'STLI', 'Steiner Limited', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (362, 'STEI', 'Steinhart', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (363, 'STOW', 'Stowa', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (364, 'STRO', 'Strom', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (365, 'STUH', 'Stuhrling', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (366, 'SWAT', 'Swatch', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (367, 'SWIM', 'Swiss Military', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (368, 'SWIT', 'Swiss Timer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (369, 'TAG ', 'TAG Heuer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (370, 'TB B', 'TB Buti', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (371, 'TEMA', 'Technomarine', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (372, 'TECH', 'Technos', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (373, 'TELL', 'Tellus', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (374, 'TEMP', 'Temption', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (375, 'TECO', 'Tempvs Compvtare', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (376, 'TEND', 'Tendence', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (377, 'TERR', 'Terra Cielo Mare', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (378, 'THE ', 'The One Binary', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (379, 'THEO', 'Theorein', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (380, 'THOM', 'Thomas Ninchritz', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (381, 'THOR', 'Thorr', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (382, 'TIFF', 'Tiffany', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (383, 'TIME', 'Timex', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (384, 'TISS', 'Tissot', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (385, 'TOMM', 'Tommy Hilfiger', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (386, 'TONI', 'Tonino Lamborghini', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (387, 'TOUR', 'Tourneau', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (388, 'TRAS', 'Traser', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (389, 'TUDO', 'Tudor', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (390, 'TUTI', 'Tutima', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (391, 'TW S', 'TW Steel', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (392, 'U-BO', 'U-Boat', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (393, 'ULYS', 'Ulysse Nardin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (394, 'UNIK', 'Unikatuhren', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (395, 'UNIO', 'Union Glashütte', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (396, 'UNIV', 'Universal Genève', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (397, 'URBA', 'Urban Jürgensen', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (398, 'URWE', 'Urwerk', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (399, 'UTS-', 'UTS-München', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (400, 'VACH', 'Vacheron Constantin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (401, 'VALB', 'Valbray', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (402, 'VALE', 'Valentino', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (403, 'VANC', 'Van Cleef & Arpels', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (404, 'VAND', 'Van Der Bauwede', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (405, 'VENT', 'Ventura', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (406, 'VERS', 'Versace', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (407, 'VICE', 'Viceroy', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (408, 'VICT', 'Victorinox Swiss Army', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (409, 'VILL', 'Villemont', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (410, 'VIXA', 'Vixa', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (411, 'VOLN', 'Volna', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (412, 'VON ', 'Von Wangenheim', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (413, 'VULC', 'Vulcain', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (414, 'WAKM', 'Wakmann', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (415, 'WALD', 'Waldan International', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (416, 'WALT', 'Waltham', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (417, 'WELD', 'Welder', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (418, 'WEMP', 'Wempe', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (419, 'WENG', 'Wenger', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (420, 'WEST', 'West End Watch Co.', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (421, 'WITT', 'Wittnauer', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (422, 'WYLE', 'Wyler', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (423, 'WYVE', 'Wyler Vetta', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (424, 'XEME', 'Xemex', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (425, 'YORK', 'York', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (426, 'YVES', 'Yves Saint Laurent', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (427, 'ZANN', 'Zannetti', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (428, 'ZENI', 'Zenith', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (429, 'ZENO', 'Zeno-Watch Basel', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (430, 'ZENT', 'ZentRa', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (431, 'ZEPP', 'Zeppelin', 1);
INSERT INTO cat_marca (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (432, 'ZODI', 'Zodiac', 1);



INSERT INTO cat_genero (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (1, 'CBRO', 'Caballero', 5);
INSERT INTO cat_genero (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (2, 'DAMA', 'Dama', 5);
INSERT INTO cat_genero (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (3, 'TMED', 'Talla media (MIDSIZE)', 5);
INSERT INTO cat_genero (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (4, 'OTRO', 'Otro', 5);


INSERT INTO cat_condiciones_generales (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (1, 'SNES', 'Sin estrenar', 3);
INSERT INTO cat_condiciones_generales (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (2, 'MBUE', 'Muy bueno', 3);
INSERT INTO cat_condiciones_generales (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (3, 'BUNO', 'Bueno', 3);
INSERT INTO cat_condiciones_generales (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (4, 'USDO', 'Usado', 3);
INSERT INTO cat_condiciones_generales (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (5, 'DFTO', 'Defectuoso', 3);
INSERT INTO cat_condiciones_generales (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (6, 'DMTR', 'Desmantelar', 3);


INSERT INTO cat_desplazamiento_comercial (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (1, 'EXLT', 'Excelente', 4);
INSERT INTO cat_desplazamiento_comercial (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (2, 'ALTO', 'Alto', 4);
INSERT INTO cat_desplazamiento_comercial (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (3, 'MEDI', 'Medio', 4);
INSERT INTO cat_desplazamiento_comercial (id_elemento, abreviatura, etiqueta, id_configuracion) VALUES (4, 'BAJO', 'Bajo', 4);


INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (1, 'SNES_EXLT', 'Sin estrenar - Excelente', 'SNES', 'EXLT', 0.9000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (2, 'SNES_ALTO', 'Sin estrenar - Alto', 'SNES', 'ALTO', 0.8500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (3, 'SNES_MEDI', 'Sin estrenar - Medio', 'SNES', 'MEDI', 0.8000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (4, 'SNES_BAJO', 'Sin estrenar - Bajo', 'SNES', 'BAJO', 0.7500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (5, 'MBUE_EXLT', 'Muy bueno - Excelente', 'MBUE', 'EXLT', 0.8500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (6, 'MBUE_ALTO', 'Muy bueno - Alto', 'MBUE', 'ALTO', 0.8000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (7, 'MBUE_MEDI', 'Muy bueno - Medio', 'MBUE', 'MEDI', 0.7500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (8, 'MBUE_BAJO', 'Muy bueno - Bajo', 'MBUE', 'BAJO', 0.7000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (9, 'BUNO_EXLT', 'Bueno - Excelente', 'BUNO', 'EXLT', 0.8000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (10, 'BUNO_ALTO', 'Bueno - Alto', 'BUNO', 'ALTO', 0.7500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (11, 'BUNO_MEDI', 'Bueno - Medio', 'BUNO', 'MEDI', 0.7000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (12, 'BUNO_BAJO', 'Bueno - Bajo', 'BUNO', 'BAJO', 0.6500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (13, 'USDO_EXLT', 'Usado - Excelente', 'USDO', 'EXLT', 0.7500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (14, 'USDO_ALTO', 'Usado - Alto', 'USDO', 'ALTO', 0.7000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (15, 'USDO_MEDI', 'Usado - Medio', 'USDO', 'MEDI', 0.6500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (16, 'USDO_BAJO', 'Usado - Bajo', 'USDO', 'BAJO', 0.6000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (17, 'DFTO_EXLT', 'Defectuoso - Excelente', 'DFTO', 'EXLT', 0.5500, 0, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (18, 'DFTO_ALTO', 'Defectuoso - Alto', 'DFTO', 'ALTO', 0.5000, 0, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (19, 'DFTO_MEDI', 'Defectuoso - Medio ', 'DFTO', 'MEDI', 0.4500, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (20, 'DFTO_BAJO', 'Defectuoso - Bajo ', 'DFTO', 'BAJO', 0.4000, 1, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (21, 'DMTR_EXLT', 'Desmantelar - Excelente ', 'DMTR', 'EXLT', 0.2000, 0, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (22, 'DMTR_ALTO', 'Desmantelar - Alto ', 'DMTR', 'ALTO', 0.1500, 0, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (23, 'DMTR_MEDI', 'Desmantelar - Medio ', 'DMTR', 'MEDI', 0.1000, 0, 6);
INSERT INTO cat_matriz_coordenadas (id_elemento, abreviatura, etiqueta, condicion, desplazamiento, factor, valida, id_configuracion) VALUES (24, 'DMTR_BAJO', 'Desmantelar -  Bajo', 'DMTR', 'BAJO', 0.0500, 0, 6);


INSERT INTO cat_refrendo (id_elemento, abreviatura, etiqueta, tipo_reloj, numero, id_configuracion) VALUES (1, 'REF_AUTO', 'Refrendos para reloj automaitco', 'AUTO', 3, 7);
INSERT INTO cat_refrendo (id_elemento, abreviatura, etiqueta, tipo_reloj, numero, id_configuracion) VALUES (2, 'REF_CURZ', 'Refrendos para reloj de cuarzo', 'CURZ', 0, 7);
INSERT INTO cat_refrendo (id_elemento, abreviatura, etiqueta, tipo_reloj, numero, id_configuracion) VALUES (3, 'REF_MANL', 'Refrendos para reloj manual', 'MANL', 3, 7);
